from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Protocol

class State(Protocol):
    def on_enter(self) -> None: ...
    def on_exit(self) -> None: ...
    def handle_event(self, event) -> None: ...
    def update(self, dt: float) -> None: ...
    def render(self, screen) -> None: ...

@dataclass
class StateTransition:
    next_state: Optional[State] = None
    pop: bool = False
